# This workflow will build a .NET project and attach the output to a release
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on:
  release:
    types: [created]  # Trigger the workflow when a release is created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload CMDHelper.exe
      uses: actions/upload-artifact@v3
      with:
        name: CMDHelper-executable
        path: bin/Release/net462/CMDHelper.exe
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: bin/Release/net462/CMDHelper.exe
        asset_name: CMDHelper.exe
        asset_content_type: application/octet-stream
